### ISSUE TITLE
Chunk unload takes O(n) instead of O(1)

### ISSUE THREAD

**Issue by Electroid** [Electroid/SportPaper#111] opened 2021-12-28 05:44 UTC
This patch makes chunk unloading O(n) by using a `LongArraySet` instead of being O(1), this means the server slows down considerably the more getChunk calls occur and the more chunks get on the unload queue, this had been fixed in https://github.com/Electroid/SportPaper/pull/19 and is a bug that got reintroduced in this pr

Next time when editing lines that already have a `// sportpaper` comment be more caureful about editing them and lookup the original patches to see why they were already changed, don't mindlessly override the previous changes

_Originally posted by @Pablete1234 in https://github.com/Electroid/SportPaper/issues/73#issuecomment-1001230104_

**Comment by linsaftw** [comment] 2021-12-29 15:09
This was changed because of a crash caused by the fastutil patch.

We need to investigate the cause of the crash and fix it.

**Comment by Pablete1234** [comment] 2021-12-29 19:22
The original change was to migrate to fast util collections, as seen in:
https://github.com/Electroid/SportPaper/blob/master/patches/server/0176-Use-fast-util-collections.patch

The issue is that it migrated to a LongArraySet, which is a performance issue, and, in #19, it was fixed by introducing:
https://github.com/Electroid/SportPaper/commit/4d63808a241c9dc629245845057feb32259350c9#diff-8b64ebdf0e0949225a0d0109c31243017b5e8c0d6ea4e6abfd3650c1df8a22ff

which changes it from a LongArraySet into a LongOpenHashSet, which solves the performance issue

Later in #73 , it was, again, changed back to the old LongArraySet which kills server performance

**Closed** 2022-06-07 01:40 UTC
